fixed emqx config file
having a comma after 'name = "bcrypt"' breaks the emqx container with the following error on boot

```
ERROR: call_hocon_failed: -s emqx_conf_schema -c /opt/emqx/etc/emqx.conf multi_get node.data_dir node.name node.cookie node.db_backend cluster.proto_dist node.dist_net_ticktime
```

Line 11 is the bcrypt line. 

Remove the comma and it fires right up.